from django.core.exceptions import ValidationError


def validate_reservation_availability():
    pass
